# Generated by Django 5.2.4 on 2025-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('about', 'О компании'), ('contacts', 'Контакты'), ('home', 'Главная'), ('custom', 'Пользовательская')], default='custom', max_length=20, verbose_name='Тип страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(help_text='HTML контент страницы', verbose_name='Содержимое'),
        ),
    ]
