# Generated by Django 5.2.4 on 2025-07-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('product_id', models.CharField(max_length=50, verbose_name='ID товара')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('product_code', models.CharField(max_length=100, verbose_name='Код товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Запрос цены товара',
                'verbose_name_plural': 'Запросы цены товаров',
                'ordering': ['-created_at'],
            },
        ),
    ]
