# Generated by Django 5.2.4 on 2025-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_priceinquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на звонок', 'verbose_name_plural': 'Заявки на звонок'},
        ),
        migrations.AddField(
            model_name='priceinquiry',
            name='request_type',
            field=models.CharField(choices=[('call', 'Заявка на звонок'), ('price', 'Запрос цены товара')], default='call', max_length=10, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='priceinquiry',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='priceinquiry',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID товара'),
        ),
        migrations.AlterField(
            model_name='priceinquiry',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название товара'),
        ),
    ]
