# Generated by Django 5.2.4 on 2025-07-31 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_subcategory_product_artikyl_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OeKod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oe_kod', models.CharField(db_index=True, max_length=100, verbose_name='Номер аналога OE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oe_analogs', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Аналог OE',
                'verbose_name_plural': 'Аналоги OE',
                'indexes': [models.Index(fields=['oe_kod'], name='shop_oekod_oe_kod_61c6c7_idx')],
                'unique_together': {('product', 'oe_kod')},
            },
        ),
    ]
