# Generated by Django 5.2.4 on 2025-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_oekod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/', verbose_name='CSV файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Всего строк')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='Обработано строк')),
                ('created_products', models.IntegerField(default=0, verbose_name='Создано товаров')),
                ('updated_products', models.IntegerField(default=0, verbose_name='Обновлено товаров')),
                ('error_log', models.TextField(blank=True, verbose_name='Лог ошибок')),
            ],
            options={
                'verbose_name': 'Импорт файл',
                'verbose_name_plural': 'Импорт файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
