# Generated by Django 5.2.4 on 2025-07-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_importfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='current_row',
            field=models.IntegerField(default=0, verbose_name='Текущая строка'),
        ),
        migrations.AddField(
            model_name='importfile',
            name='error_count',
            field=models.IntegerField(default=0, verbose_name='Количество ошибок'),
        ),
        migrations.AddField(
            model_name='importfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='pending', max_length=50, verbose_name='Статус'),
        ),
    ]
